{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector: {{- toYaml .Values.networkPolicy.podSelector | nindent 4 }}
  policyTypes:
  {{- range .Values.networkPolicy.policyTypes }}
    - {{ . }}
  {{- end }}
  ingress:
  {{- if .Values.networkPolicy.ingress }}
  {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
    []
  {{- end }}
  egress:
  {{- if .Values.networkPolicy.egress }}
  {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
    []
  {{- end }}
{{- end }}
